### ISSUE TITLE
What is new?

### ISSUE THREAD

**Issue by Yolanda22** [Deepflex/android_kernel_elephone_p9000#1]
What have you changed ?
what is the diffferent from Original Realesed Kernal

**Comment by Deepflex** [comment]
Fully fixed all bugs when you compilling outside MTK sources
Disabled AAL
Added CM support
Added F2FS support
Fixed FC
And a lot of i can't remember, more stuff in Flexy kernel

**Comment by JonnyVR1** [comment]
Closed as its not an issue
