### ISSUE TITLE
[Request] Add lulzactive, smartassv2 governors support and missing cpu-freq support

### ISSUE THREAD

**Issue by AreYouLoco** [Deepflex/android_kernel_elephone_p9000#10]
You can do it by simplly merging this:

https://github.com/broodplank/samsung-kernel-msm7x30/commit/bd319103c20c9a9357852d6f535aaa999cee867a

it depends on cpufreq which is also not supported.

I think this is a good start for cpu powersaving on Elephone p9000

**Comment by AreYouLoco** [comment]
I made pull request for that

**Comment by Deepflex** [comment]
Hello.Thx

**Comment by AreYouLoco** [comment]
You need to make some additional changes in .config file.
For sure add cpu-freq support and enable governors in config.

It depends on CONFIG_CPUFREQ_DT=y

**Comment by AreYouLoco** [comment]
I am not a programmer and there were merge conflicts I am sorry but I cannot fix.
Please close for now.
