### ISSUE TITLE
Telegram username

### ISSUE THREAD

**Issue by av2k** [Deepflex/android_kernel_elephone_p9000#13]
Dear Deepflex, is it possible to reach you via Telegram? If so, please leave me your username and delete this ticket afterwards. :-) I'd like to ask you a few questions about P9000's LineageOS future and I can possibly offer you an OTA server in Germany. Thank you.

**Comment by Deepflex** [comment]
Hello
Thank you very much!)
Deepflex Maxim
Deepflex - First name
Maxim - Last name
+79994309939
