### ISSUE TITLE
This is not the source.

### ISSUE THREAD

**Issue by not-a-user** [Deepflex/android_kernel_elephone_p9000#2]
I understand this is the "source" for the P9000 kernel which you ship with your CM13 ROM over at xda.

However, there are lots of precompiled (`.o_shipped`) object files in `drivers/misc/mediatek`. It seems to me, that most of the Mediatek kernel modifications are actually not included as source code (no `.c` files).

By the way, where did you get this?

Is Elephone not required to release the full kernel source as soon as they ship the phone, according to the GPL?

**Comment by Deepflex** [comment]
This drivers is not afforded to GPL
(Author right's)
