### ISSUE TITLE
Invalid ccmni rx channel

### ISSUE THREAD

**Issue by andyrichardson** [Deepflex/android_kernel_elephone_p9000#7]
I'm currently getting the following error in my bug log:

```
<3>[18229.373403]  (0)[774:gsm0710muxd][ccci1/net][Error:77]get_ccmni_idx_from_ch:invalid ccmni rx channel(0x60)
<3>[18229.373447]  (0)[774:gsm0710muxd][ccci1/net][Error:1041]ccmni_dump:CCMNI rx(96) skb ch error
```

I'm assuming this is related to one of the following issues I am currently experiencing:
- Lack of HSPA+
- EE not showing up on 'network operators' manual selection
- Error when manually setting GSM/UMTS band 

**Update:**
Delving further into this, I've found the following error also which I believe may be related.

```
09-02 17:03:29.022  1597  1730 D RilRequest: [7043]< REQUEST_GET_NEIGHBORING_CELL_IDS error: com.android.internal.telephony.CommandException: RADIO_NOT_AVAILABLE ret=
09-02 17:03:29.030  1597  1730 D RilRequest: [7044]< RIL_REQUEST_GET_CELL_INFO_LIST error: com.android.internal.telephony.CommandException: RADIO_NOT_AVAILABLE ret=
09-02 17:03:29.030  1597  1597 D GsmSST  : [GsmSST] EVENT_GET_CELL_INFO_LIST: error ret null, e=com.android.internal.telephony.CommandException: RADIO_NOT_AVAILABLE
```

**Comment by SchizoDuckie** [comment]
Do you have any more info on this? Do your fixes resolve the issues?

My Vernee Apollo Lite is having this exact issue, and I'm referring them to this issue to send them on the (hopefully) right path to getting a stable cell connection on this thing

**Comment by andyrichardson** [comment]
HSPA and HSPA+ is working on the latest build - Closing

**Comment by SchizoDuckie** [comment]
Thank you very much. You're about to make a lot of people very happy.

**Comment by SchizoDuckie** [comment]
Sorry to disturb you again, but the repo seems to have been reset to a point before the patches that were previously attached here. Do you maybe have a backup or something I could fork?
