### ISSUE TITLE
Invalid battery current reporting

### ISSUE THREAD

**Issue by andyrichardson** [Deepflex/android_kernel_elephone_p9000#8]
**Issue**
The phone is reporting an incorrect battery current average. 

**Description** 
When charging, the phone seems to charge at a constant rate (I'd estimate 2amps but I do not have the equipment to test this) but the system reports an incremental drop in current. This incremental drop is persistent and eventually leads to the current average being below 0 despite the battery charge level increasing during a charge.

I mentioned this on the [CM13 release thread](http://forum.xda-developers.com/elephone-p9000/development/rom-21-07-cyanogenmod-13-0-android-6-0-t3423518) but I believe it is related to the kernel rather than the ROM.

---

**Replication**
To test, run the following script (or similar) using ADB over wifi and ensure your phone is not plugged in:

```
#!/bin/bash

while true
do
    adb shell cat /sys/class/power_supply/battery/BatteryAverageCurrent | tee -a battery_amp.log
    sleep 10
done
```

Once the script starts, plug your phone into a charging source. You'll see the initial/real current but as time goes on, the current will continue to drop. Here were my results:

```
0
0
1858
1858
1700
1621
1542
1461
1461
1297
1297
1220
1056
975
975
812
812
645
645
483
401
401
237
158
75
-6
-6
-170
-253
-336
-420
-420
-440
0
0
```

You can see towards the end of the log, as I unplugged my charger, the current went back up to the initial value of 0. This implies that charging the draws current - clearly this is not the case.

**Comment by JonnyVR1** [comment]
This is indeed an issue related to the kernel, I've pointed leskal in the general direction of the fix and he is working on it.

**Comment by AreYouLoco** [comment]
I can also confirm this. I used application Ampere to measure the ampere current.
Application reported incorrect values.

**Comment by leskal** [comment]
Fixed: https://github.com/leskal/android_kernel_elephone_p9000/commit/e55ef0111305a1a49e14ff9caff6c103346e6894
