### ISSUE TITLE
PE+ Charging not working

### ISSUE THREAD

**Issue by robot-army** [Deepflex/android_kernel_elephone_p9000#9]
The PE+ protocol is not working on this build. With an old version of the phone stock FW I was able to observe current pulses which would request that a compatible charger should increase its voltage in 0.2 V steps (see page 14 here - warning PDF link - http://www.dianyuan.com/upload/community/2015/02/02/1422849155-88443.pdf )

On the latest OTA, and on build 4 of cm13 for the p9000, this behaviour is not observed. The current draw goes straight for 1.6-ish amps on plugging the phone in. There are no requests to increase the voltage from 5V, so even a compatible PE+ charger wouldn't charge the phone as it should.

**Comment by leskal** [comment]
Can you try DarkSense kernel ?

**Comment by robot-army** [comment]
Absolutely can try, but I'm a hardware engineer so will need some
hand-holding :)

Where do I get it? How do I install it?

Cheers!

On 3 Oct 2016 14:56, "Alex Kalles" notifications@github.com wrote:

Can you try DarkSense kernel ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/Deepflex/android_kernel_elephone_p9000/issues/9#issuecomment-251112068,
or mute the thread

**Comment by leskal** [comment]
http://forum.xda-developers.com/elephone-p9000/development/kernel-darksense-p9000-kernel-1-0-0-3-t3456935

Flash the zip through TWRP

**Comment by robot-army** [comment]
Thanks for the link Alex,

I've installed CM13 as per the steps (starting at step 1, doing the spflash
stuff etc)
http://forum.xda-developers.com/elephone-p9000/development/rom-21-07-cyanogenmod-13-0-android-6-0-t3423518

What do I need to do to install this darksense stuff? Copy the zip to the
SD card, boot into recovery and 'apply update'? Do something else?

This is my first toe-dipping into android as anything other than a user, so
please bear with me, sorry for my dumb questions.

Thanks again,
Ryan

**Comment by robot-army** [comment]
http://forum.xda-developers.com/showpost.php?p=68696266&postcount=47

Is that the right order? Do I need to "exchange 3 - 4, and 6 - 7" as the
next post says? Can you tell how brand new I am at this now? :)

**Comment by leskal** [comment]
Follow the 3 first steps from the post you send me

**Comment by robot-army** [comment]
OK, I appear to have sucessfully flashed the kernel, I'm not sure how to
tell, but I can tell you that I saw something in recovery saying 'Deepflex'
and 'success' a lot, and PE+ still doesn't work.

**Comment by robot-army** [comment]
Sorry, my bad, darksense, and I've just checked in 'about phone' and it
says 3.18.42-DarkSense-1.2.0....

**Comment by leskal** [comment]
Ok, thanks for the testing, i will look into it

**Comment by robot-army** [comment]
I'm just about to confirm my setup, just incase I'm doing something dumb.
Is there a stock rom that we know does PE+? I haven't been able to get it
back since it went with the OTA, but I think it's working in 0715, so I'm
downloading that from here now:

http://bbs.elephone.hk/thread-11767-1-1.html

**Comment by robot-army** [comment]
I'll do a little video of what to look for on a bench supply if the stock
rom works, then you can test it for yourself (all you need is a cheap bench
supply, usb cable and a pair of wirecutters!)

**Comment by robot-army** [comment]
That stock rom didn't do it. Downloading
http://bbs.elephone.hk/thread-10093-1-2.html now.

I've definitely tested this hardware before, and definitely saw the PE+
current modulation behaviour, and definitely saw it running at 1.? A input
at 12 V. I'm beginning to doubt it myself!!

**Comment by leskal** [comment]
I have may found the prob, we have shipped drivers(compiled) and we can't modify them, JonnyXDA has work with it and soon we will have actual code and not binary files, for the time being we can't do anything but to collect bugs, soon i will send you to test a kernel PE+

**Comment by robot-army** [comment]
OK, cool, let me check my setup before going too much further though. I'm
going crosseyed! 90% there.

I'm in freenode #android-root now if ur online?

**Comment by leskal** [comment]
I tried to found you at freenode but i can't search me as "leskal"

Also i send you to test a kernel for PE+ but be careful in the kernel i send you the usb connection to pc doesn't work
[3.18.30-TEST-PE.zip](https://github.com/Deepflex/android_kernel_elephone_p9000/files/507383/3.18.30-TEST-PE.zip)

**Comment by robot-army** [comment]
YES this one does it - Stock rom with working PE+ -
http://bbs.elephone.hk/thread-10093-1-2.html

https://youtu.be/JSIPXabJEFY

**Comment by robot-army** [comment]
Any update on this? There's still a lot of fud floating about on PE+ stuff for this phone on the forums.

**Comment by Deepflex** [comment]
Fixed

**Comment by leskal** [comment]
Have you test it?

**Comment by Deepflex** [comment]
Np, but u can test it, i'm sure, that phone will charge more faster. Because now i'm not at home
